import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import ThemeSwitch from "../components/Utilities/ThemeSwitch";
import Providers from "./providers";

const poppins = Poppins({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "FRENIME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} bg-primary dark:bg-dark-primary`}>
        <Providers>
          <Navbar />
          <main className="px-4 md:px-6">{children}</main>
          <ThemeSwitch />
        </Providers>
      </body>
    </html>
  );
}
